cluster:
    name: dingo
exchange:
    host: XXXXXX
    port: 19181
server:
    dataPath: /opt/dingo/coordinator
    raft:
        port: 9181
        initRaftSvrList: coordinator3:9181,coordinator2:9181,coordinator1:9181
    schedule:
        autoSplit: true
